# File automatically generated by qutebrowser

config.set('content.autoplay', True, 'https://discord.com')
config.set('content.desktop_capture', True, 'https://app.element.io')
config.set('content.desktop_capture', True, 'https://discord.com')
config.set('content.media.audio_capture', True, 'https://stoat.chat')
config.set('content.media.audio_video_capture', True, 'https://app.element.io')
config.set('content.media.video_capture', True, 'https://discord.com')
config.set('content.notifications.enabled', False, 'https://discord.com')
config.set('content.notifications.enabled', False, 'https://fluffychat.im')
config.set('content.notifications.enabled', False, 'https://stoat.chat')
config.set('content.register_protocol_handler', True, 'https://mail.google.com?extsrc=mailto&url=%25s')
