# File automatically generated by qutebrowser

config.set('content.desktop_capture', True, 'http://localhost:8073')
config.set('content.desktop_capture', True, 'https://discord.com')
config.set('content.media.audio_capture', True, 'http://localhost:5174')
config.set('content.media.video_capture', True, 'https://discord.com')
config.set('content.register_protocol_handler', True, 'https://mail.google.com?extsrc=mailto&url=%25s')
